# Generated by Django 5.2.8 on 2025-12-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
