# Generated by Django 5.2.8 on 2025-12-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default_cover_page.png', upload_to='books'),
        ),
    ]
